FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# monitor


## 全站发电量 [/station/power]



### history message[POST]

+ Request  (application/json)

        {
            "dateType":"day"
            "date":"2016-05-04",
        }


+ Response 200 (application/json)

        {   
            "title":{"text":"总发电量","show":true},
            "xAxis":["11时","12时","13时","14时","15时","16时"],
            "series":{
                        "type":"bar",
                        "name":"日发电量",
                        "value":[200,300,400,200,100,300]
                    }
                   
        }
        

 
## 全站日期时间范围 [/station/range]

###  message [GET]

+ Response 200 (application/json)

        {
            "beginDate":"2010-07-01", 
            "endDate":"2017-07-18"
        }
        


## 单个站点历史图表信息 [/eachStation/]

### history message [POST]

+ Request  (application/json)

        {
            "stationId":123,
            "date":"2017-06-14",
            "dateType":"month"
        }


+ Response 200 (application/json)

        [
            {   
                "id":1,
                "title":{"text":"发电量kw/h","show":true},
                "xAxis":["11时","12时","13时","14时","15时","16时"],
                "series":{
                            "type":"bar",
                            "name":"日发电量",
                            "value":[200,300,400,200,100,300]
                        }
                   
            },
             {   
                "id":2,
                "title":{"text":"电流/A","show":true},
                "xAxis":["11时","12时","13时","14时","15时","16时"],
                "series":{
                            "type":"bar",
                            "name":"电流",
                            "value":[200,300,400,200,100,300]
                        }
                   
            },
             {   
                "id":3,
                "title":{"text":"电压/V","show":true},
                "xAxis":["11时","12时","13时","14时","15时","16时"],
                "series":{
                            "type":"bar",
                            "name":"电压",
                            "value":[200,300,400,200,100,300]
                        }
                   
            }
        ]
        

        
## 单个站点实时图表信息 [/eachStation/live]

### 实时数据配置 [GET] 加载配置

+ Request  (application/json)

        {
            "stationid":123
            "live":"true"
        }


+ Response 200 (application/json)

        [
            {   
                "id":1,
                "title":{"text":"电压/V","show":true},
                "series":{"type":"line","name":"电压"}
            },
             {   
                "id":2,
                "title":{"text":"电流/A","show":true},
                "series":{"type":"line","name":"电流"}
                        
                   
            },
            {   
                "id":3,
                "title":{"text":"发电量kw/h","show":true},
                "series":{"type":"bar","name":"发电量"}
                        
                   
            }
        ] 
        
### 实时数据-polling [POST] 更新数据

+ Request  (application/json)

        {
            "stationid":123
            "live":"true"
        }


+ Response 200 (application/json)

        [
            {"id":1,"xAxis":"17分","value":200},
            {"id":2,"xAxis":"17分","value":300},
            {"id":3,"xAxis":"17分","value":400}
        ]